---
# Standard Docker build and push workflow
# https://github.com/marketplace/actions/build-and-push-docker-images

name: docker-build

env:
  IMAGE_NAME: "drupal-postgres"

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'example/**'
      - 'README.md'
      - 'docs/**'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}"